/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class client_halouhuandian_app15_CanAndSer */

#ifndef _Included_client_halouhuandian_app15_CanAndSer
#define _Included_client_halouhuandian_app15_CanAndSer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     client_halouhuandian_app15_CanAndSer
 * Method:    openCan
 * Signature: ()Ljava/io/FileDescriptor;
 */
JNIEXPORT jobject JNICALL Java_client_halouhuandian_app15_CanAndSer_openCan
  (JNIEnv *, jclass);

/*
 * Class:     client_halouhuandian_app15_CanAndSer
 * Method:    openSer
 * Signature: (Ljava/lang/String;I)Ljava/io/FileDescriptor;
 */
JNIEXPORT jobject JNICALL Java_client_halouhuandian_app15_CanAndSer_openSer
  (JNIEnv *, jclass, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
